The European Union on the world stage  Az Európai Unió a nemzetközi porondon 
In economic, trade and monetary terms, the European Union has become a major world power.  Gazdasági, kereskedelmi és monetáris értelemben az Európai Unió vezetõ világhatalommá nõtte ki magát. 
It has considerable influence within international organisations such as the World Trade Organisation (WTO), the specialist branches of the United Nations (UN) and at world summits on the environment and development.  Az Unió jelentõs befolyással rendelkezik olyan nemzetközi szervezetekben és fórumokon, mint a Kereskedelmi Világszervezet (WTO), az ENSZ szakosodott intézményei és a környezetvédelemmel és a fejlõdéssel foglalkozó nemzetközi csúcstalálkozók. 
Some have described the EU as an economic giant but a ‘political dwarf’.  Vannak azonban, akik az EU-t nem gazdasági óriásnak, hanem politikai értelemben vett „törpének” tekintik. 
This is an exaggeration.  Ez azonban túlzás. 
Nevertheless, it is true that the EU member states have a long way to go, in diplomatic and political terms, before they can speak with one voice on major issues like peace and stability, terrorism, the Middle East, relations with the United States and the role of the UN Security Council.  Igaz ugyan, hogy az uniós tagállamoknak politikai és diplomáciai értelemben még nagy utat kell megtenniük, míg egy emberként hallathatják hangjukat olyan hangsúlyos kérdésekben, mint a béke és a stabilitás, a terrorizmus, a Közép-Kelet, az Egyesült Államokkal folytatott kapcsolatok és az ENSZ Biztonsági Tanácsának szerepe. 
The EU countries retain full national sovereignty over their armed forces.  Az uniós tagállamok teljes nemzeti szuverenitással rendelkeznek saját fegyveres testületeik felett. 
Their defence systems are firmly in the hands of the national governments, and the only ties between them are those forged within alliances such as NATO.  Védelmi rendszereik megkérdõjelezhetetlenül nemzeti kormányaik irányítása alá tartoznak, s e kormányok közötti egyetlen kapocs az általuk alkotott szövetségek (pl. a NATO) keretében megkötött egyezmények. 
An embryonic common defence policy  Gyermekcipõben járó közös védelmi politika 
The Common Foreign and Security Policy (CFSP) and the European Security and Defence Policy (ESDP), provided for in the Maastricht and Amsterdam treaties, define the EU’s main tasks in the area of defence.  A védelem területén az Unió legfontosabb teendõit és feladatait a Maastrichti és az Amszterdami szerzõdésben lefektetett közös kül- és biztonságpolitika (KKBP), illetve az Európai biztonsági és védelmi politika határozzák meg. 
On this basis, the EU has developed its ‘second pillar’ – the policy domain in which action is decided by inter-governmental agreement and in which the Commission and Parliament play only a minor role.  Ez az alapja az Unió ún. második pillérének, amely olyan politikai terület, ahol a fellépésekrõl kormányközi megállapodások döntenek, és amelyben a Bizottság és a Parlament szerepe csekély. 
Decisions in this domain are taken by consensus, allowing individual states to abstain.  Az e területen meghozott döntések konszenzussal születnek, így az egyes tagállamok akár tartózkodhatnak is a szavazástól. 
In the early 21st century, the EU’s political and strategic landscape looks like this:  A 21. század elején az Unió politikai és stratégiai tervének fõbb irányvonalai a következõk: 
With Russia following the path of friendship with the western world, and the former Communist countries of central and eastern Europe joining NATO and the EU almost simultaneously, more than half a century of Cold War is well and truly behind us.  Oroszország folyamatosan nyit a nyugati világ felé, a NATO-hoz és az Unióhoz szinte egyszerre csatlakoznak közép-kelet európai valamikori kommunista országok.  Igen, a hidegháború közel fél évszázada véget ért. 
The continent of Europe is becoming peacefully united, and European countries are working together to fight international crime such as people smuggling and money laundering.  Az öreg kontinens egyesülése békésen zajlott, és ma már az európai országok együtt veszik fel a harcot a nemzetközi bûnözés (pl. embercsempészet és pénzmosás) ellen. 
The EU has formed an organised partnership with its large neighbours, such as Russia and the Ukraine, which have no prospect of joining the European Union – at least in the medium term.  Az Unió szervezett partneri viszonyt ápol olyan hatalmas területû szomszédaival, mint Oroszország és Ukrajna, amely országok – legalábbis középtávon – nem igen bízhatnak a csatlakozásban. 
The EU member states want to establish a European Security and Defence Policy in accordance with the Treaties.  Az uniós tagállamok a Szerzõdésekkel összhangban létre kívánják hozni az Európai Biztonsági és Védelmi politikát. 
In December 1999, the Helsinki European Council set the EU a specific objective: to be able, by 2003, to deploy within 60 days a force of up to 60 000 troops, with naval and air support, and to sustain it for at least one year.  1999 decemberében a helsinki Európai Tanács a következõ célt tûzte ki maga elé: 2003-ig egy közel 60 000 fõbõl álló hadtest legkevesebb 60 napon belüli bevetési tervének kidolgozása, légi és tengeri támogatással, továbbá e hadmûvelet fenntartása legalább egy évig. 
This rapid reaction force is not a ‘European army’: it is made up of contingents from the national armed forces.  But it is coordinated by a Political and Security Committee (PSC), a Military Committee (EUMC) and a military staff (EUMS), under the authority of the Council and located in Brussels.  Ez a gyorsreagálású hadtest nem egy „Európai hadsereg”, hanem a nemzeti fegyveres erõk kontingenseibõl alakult fegyveres testület, amelyet a brüsszeli központú Politikai és Szociális Bizottság, a Katonai Bizottság és az Európai Unió Katonai Törzse koordinálna, és a Tanács irányít. 
This give the Union a political and military tool for carrying out certain specific types of task – humanitarian and rescue missions outside Europe, peace-keeping operations and other crisis management tasks including peacemaking.  Ezzel az Unió egy olyan politikai és katonai eszköz birtokába jutna, amellyel az Európán kívüli humanitárius és mentési feladatokat és küldetéseket, a békefenntartói mûveleteket, valamint egyéb válságkezelõ (és béketeremtõ) tevékenységeket is el tud látni. 
The United States accepts that, for military action in which America does not want to be involved, Europe can use some of NATO’s logistical capacity such as its intelligence, communications, command and transport capabilities.  Az Egyesült Államok hozzájárulásával azokban a katonai mûveletekben, melyekben az USA nem kíván részt venni, Európa használhatja a NATO logisztikai eszközeit (pl. a katonai hírszerzés és elhárító szolgálat, hírközlés és szállítási felszerelések). 
Actual defence and deterrence capabilities, such as the nuclear weapons owned by France and the United Kingdom, remain under national control.  A jelenlegi védelmi és elrettentési eszközök, mint a Franciaország és az Egyesült Királyság birtokában levõ nukleáris fegyverek, továbbra is e tagállamok nemzeti felügyelete alá tartoznak. 
As military technology becomes ever more sophisticated and expensive, EU governments will find it increasingly necessary to work together on arms manufacture.  A katonai technológia kifinomultabbá és költségesebbé válásával egyre nagyobb szükség lenne arra, hogy a tagállamok összevonják fegyvergyártási tevékenységeiket. 
Moreover, if their armed forces are to carry out joint missions, their systems must be interoperable and their equipment sufficiently standardised.  Mitöbb, ha a tagállamok haderõi közös bevetésekben vesznek részt, rendszereik egymás között is átjárhatók lesznek, felszereléseik pedig sikeresen szabványosíthatók. 
The attacks on Washington and New York on 11 September 2001, and the terrorist violence that has struck many parts of the world since then, have profoundly altered the strategic landscape.  A 2001. szeptemberi, Washington és New York elleni terrortámadások és az azután világszerte elharapódzó terrorista erõszak mély nyomot hagyott a stratégiai terven. 
European countries are working more closely together to exchange information that will help prevent such attacks.  Az európai országok ezentúl még szorosabb együttmûködésben munkálkodnak az ehhez hasonló támadások megelõzését szolgáló információcserén. 
Since the fight against terrorism is a global priority, Europe today is going beyond its traditional alliances, working not only with the United States but also with many other countries around the world to support democracy and human rights.  Mivel a terrorizmus elleni nemzetközi harc az egyik legfontosabb feladattá lépett elõ, a demokrácia és az emberi jogok védelmében Európa, messze túlmutatva hagyományos szövetségesi keretein, nem csupán az Egyesült Államokkal mûködik együtt, hanem a világ számos más országával is. 
Given this shifting strategic landscape, the European Union is trying to find the right balance between its different national traditions in the field of security and defence policy.  E változékony stratégiai helyzet következtében az Európai Unió folyamatosan törekszik a helyes egyensúly megtalálására a különbözõ tagállamok eltérõ hagyományai között a biztonsági és védelmi politika területén. 
"“If I want to talk to Europe, who do I phone?”"  "Kinek telefonáljak, ha beszélni akarok Európával?" 
The proposed EU Constitution would create the post of EU Foreign Affairs Minister, thus giving Europe a much clearer identity.  A tervezett európai Alkotmányban szerepel az európai külügyminiszteri poszt létrehozása, amely megerõsítené Európa „személyiségét”. 
The Foreign Minister would be empowered to speak for the Union in the international arena and would be a member of the European Commission as well as the High Representative for the Common Foreign and Security Policy.  Az európai külügyminiszteri poszt betöltõje a nemzetközi porondon is képviselné az Unió érdekeit; betöltõje tagja lenne az Európai Bizottságnak, és ugyanakkor a Közös Kül- és Biztonságpolitika Fõképviselõje is õ lenne. 
This would answer the question famously asked by Henry Kissinger in the 1970s: “If I want to talk to Europe, who do I phone?”  Ez választ jelentene Henry Kissinger ’70-es években feltett híres kérdésére, amely így hangzott: Kinek telefonáljak, ha beszélni akarok Európával? 
The Treaty of Amsterdam also tried to set up a procedure introducing enough flexibility into the CFSP area.  Az Amszterdami szerzõdés egy másik újítása, hogy olyan eljárást vezet be, amely kellõ rugalmasságot ad a közös kül- és biztonságpolitikai területnek. 
‘Enhanced cooperation’ would enable a group of countries to go ahead with action in which other member states did not wish to be involved – because of their tradition of neutrality, for example.  Ezzel a „megerõsített együttmûködésnek” nevezett politikával országok egy csoportja olyan kérdésekben léphet fel, amely kérdésekben más tagállamok – pl. hagyományos semlegességük miatt – nem kívánnak részt venni. 
The trouble with this apparently pragmatic solution is that the cohesiveness of the Union as a whole and its credibility on the world stage would be undermined if European foreign policy became a matter of ‘variable geometry’.  Ezzel a látszólag pragmatikus megoldással azonban van egy probléma: az Unió kohéziója és a nemzetközi porondon kivívott szavahihetõsége foroghat kockán, ha az európai külpolitika „változó geometriájú” kérdéssé válik. 
Moreover, there would be an increased risk of breaking the link between the EU’s internal policies (managing the single market, competition policy, economic and monetary union, internal security, etc.) and its external policies (trade, development aid, diplomacy and defence).  Mi több, annak is megnõ a veszélye, hogy az Unió belsõ politikái (az egységes piac irányítása, a versenypolitika, a gazdasági és monetáris unió, a belsõ biztonság stb.) és külpolitikai tevékenysége (kereskedelem, fejlesztési segély, diplomácia és védelmi politika) közötti kapcsolat törést szenved. 
For the future, it is essential that Europeans act in unison and have a policy that is clear for all to see.  Mindenesetre a jövõre nézve rendkívül fontos, hogy az európai polgárok egyetértésben és összhangban lépjenek fel, egy valamennyiük számára világos politikát követve. 
The EU countries need to speak with one voice, to show determination in defending their major interests and resolute solidarity in safeguarding their peoples’ destiny.  Az uniós tagállamoknak most kell egy emberként hallatni hangjukat ahhoz, hogy megmutassák, mennyire elkötelezettek érdekeik védelme és az uniós polgárok oltalmában tanúsított szolidaritás ügye iránt. 
Europe open to the world  Európa nyitott a világra 
The completion of the single market in 1993 affected the EU’s trade policy.  Az egységes piac 1993-as létrejötte következtében az Unió kereskedelmi politikája is elmélyült. 
The import restrictions that EU countries had been allowed to maintain were steadily abolished, as was the internal distribution of ‘sensitive’ imports such as textiles, steel, cars and electronic goods.  Az uniós tagállamok által fenntartott behozatali korlátozásokat, akárcsak ún. érzékeny importcikkek (textil, acél, gépkocsi és elektronikai berendezések) belsõ forgalmazását folyamatosan eltörölték. 
Once the WTO had been set up, at Europe’s instigation, it provided a permanent forum within which to settle trade disputes through multilateral negotiation.  A WTO létrehozásával egy olyan folyamatosan mûködõ fórum nyílt meg, ahol az Unió kezdeményezésére a kereskedelmi nézetkülönbségeket többoldalú tárgyalások során lehet orvosolni. 
The average weighted level of customs duties on industrial goods entering the European Union is less than 5%.  Az Európai Unió területére belépõ késztermékekre kivetett vámok súlyozott átlaga kevesebb, mint 5%. 
The EU and its world trading partners have agreed new rules on trade in services and agricultural products.  Az Unió és világkereskedelmi partnerei új szabályokat állítottak fel a szolgáltatásokkal és a mezõgazdasági termékekkel folytatott kereskedelem vonatkozásában. 
The discussions on agriculture clearly revealed the divergent views of producers on either side of the Atlantic.  A mezõgazdaságról szóló viták folyamán nyilvánvalóvá vált, hogy az Atlanti-óceán két partján mûködõ termelõk más és más nézeteket vallanak e kérdésben. 
Because the EU presented a united front in these talks, it was able to mount an effective defence of its member states’ viewpoint.  Mivel az Unió e párbeszédek során mindig egy egységes front nevében nyilatkozott meg, tagállamai nézõpontjának védelmében is hatékonyan tudott fellépni. 
The EU is a single trading bloc, and it is home to nearly half a billion consumers, with a relatively high average level of income.  As such, it is a very attractive market for exporters in other countries.  Az Unió közel fél milliárd fogyasztó otthonaként és viszonylag magas jövedelemszinttel egy egységes kereskedelmi blokkot alkot, s mint ilyen, természetesen rendkívül vonzó piac a többi ország számára. 
The EU can use this influence to persuade its trading partners to keep to the rules of the game – rules that ensure healthy competition and fair and equal access to one another’s markets.  E helyzeti elõnyének egyszerû kiaknázásával az Unió kereskedelmi partnereit azon játékszabályok betartására intheti, melyekkel garantálható az egészséges verseny, valamint az, hogy egymás piacain tisztességes módon, egyenlõ esélyekkel lépjenek fel. 
An important partner within the industrialised world  Az iparosodott világ fontos partnere 
From the United States’ point of view, the new Europe now under construction is an ally that shares the same values but also a competitor in trade and technology.  Az Amerikai Egyesült Államok Európát olyan szövetségesnek tekinti, melynek vele azonos értékei vannak, de ugyanakkor kereskedelmi és technológiai versenytárs is. 
The NATO alliance, which brings together the US and many EU countries, has helped mitigate the impact of trans-Atlantic trade disputes over farm produce, steel and the aerospace industry.  Az Egyesült Államokat és számos európai országot egy asztalhoz ültetõ NATO létrehozásával nagy mértékben sikerült csillapítani a mezõgazdasági termelés, valamint az acélipar és a repülõgépgyártás és ûrhajózás kapcsán az óceán mindkét partját lázban tartó kereskedelmi nézeteltéréseket. 
Towards the end of the 20th century, dramatic events – particularly the end of the Cold War – transformed the world of international politics.  A 20. század végén a nemzetközi színtéren gyökeres változásokat elõidézõ események (elsõsorban a hidegháború) befejeztével a nemzetközi politikai színtér is átrendezõdött. 
In these new circumstances, the members of NATO are having to re-define their relationship.  A megújult politikai körülmények között a NATO tagjai is új alapokra helyezhetik egymás közötti kapcsolataikat. 
Euro-American cooperation needs new objectives.  Az euro-atlanti együttmûködésnek pedig új célokat kell maga elé állítania. 
The allies must work together to tackle new dangers: nuclear proliferation, international terrorism, international crime such as drug trafficking, and so on.  A szövetségeseknek vállvetve kell együtt küzdeniük az olyan új veszélyforrások megfékezésre érdekében, mint a nukleáris fegyverek elterjedése, a nemzetközi terrorizmus, a világméreteket öltõ bûnözés (kábítószer-csempészet) stb. 
In terms of trade and investment, the European Union is the United States’ main partner and the only one with which it enjoys a stable relationship.  Kereskedelem és a beruházások tekintetében az Európai Unió az Egyesült Államok legfontosabb és az egyetlen olyan partnere, amellyel kiegyensúlyozott kapcsolatokat ápol. 
However, Europe has to contend with a certain tendency in the US Congress to resort to unilateral action that may threaten Europe’s global interests.  Mindezek ellenére Európának még szembe kell néznie azzal, hogy az amerikai Kongresszus alkalmanként kísértést érez az Európa átfogó érdekeit esetleg veszélyeztetõ egyoldalú fellépések végrehajtására. 
Relations between the EU and the Mediterranean countries   Az Unió kapcsolata a mediterrán országokkal 
Only a short distance from Europe, on the southern shore of the Mediterranean, are countries with which the EU has historical and cultural ties.  A Földközi tenger déli partvidékén, Európától csak egy ugrásra is vannak országok, amelyekhez Európát történelmi és kulturális kötelékek fûzik. 
There has been a good deal of migration between the two regions, and there is potential for much more.  E két térség között már eddig is számos csereirányú folyamat zajlott, de még messze nem minden területen. 
So these countries are very important partners for the EU, which has traditionally chosen to pursue a policy of Mediterranean regional integration.  Ezek az országok tehát továbbra is az Unió fontos partnerei, hiszen az EU hagyományosan és következetesen a mediterrán regionális politika elkötelezett híve. 
The EU’s Mediterranean neighbours were among the first to establish special economic and trading relations with the Union.  Az Unió mediterrán szomszédai az elsõk között léptek be az Unió gazdasági és kereskedelmi partnerei közé. 
In November 1995, a major conference was held in Barcelona, attended by all the EU member states and the countries bordering the Mediterranean (except for Libya, Albania and the countries that once formed Yugoslavia).  Az 1995. novemberében Barcelonában tartott konferencián az uniós tagállamok és a Földközi- tenger partvidéki országok képviselõi is részt vettek (kivéve Líbia, Albánia és a volt Jugoszlávia országai). 
This conference laid the foundations for a new Euro-Mediterranean partnership, involving:  Ezen a konferencián a küldöttek lefektették az új euro-mediterrán partnerség alapkövét, amely a következõ területeket öleli fel: 
Political dialogue between the participating countries and a security partnership based, in particular, on mechanisms for arms control and the peaceful resolution of conflicts.  Politikai párbeszéd egy biztonsági partneri kapcsolat a résztvevõ országok között elsõsorban a konfliktusok békés rendezésének és a fegyverzet ellenõrzésének mechanizmusára építve. 
Setting up economic and trading relations between the two regions.  The key to this is the creation of a Euro-Mediterranean free trade area by 2010, in compliance with WTO rules.  A két régió közötti gazdasági és kereskedelmi kapcsolatok erõsítése, s ehhez egy európai-mediterrán szabadkereskedelmi térség létrehozása 2010-re a WTO szabályaival betartása mellett. 
Once this happens, manufactured goods can be traded, duty free, on the trans-Mediterranean market, which will become the biggest free trade area in the world, embracing up to 800 million consumers.  Ily módon a késztermékek vámmentesen kerülhetnek a mediterrán térséget felölelõ területek piacaira, és ezzel a több, mint 800 millió fogyasztót magában foglaló térség a világ legnagyobb szabadkereskedelmi térsége lehet. 
Partnership in social, cultural and similar fields.  Partnerség szociális, kulturális és hasonló területeken. 
Under the MEDA programme, the EU is granting the Mediterranean countries financial assistance worth €5.3 billion over the period 2000-2006.  A MEDA program keretében az Unió a 2000-2006-ig terjedõ idõszakban mintegy 5,3 milliárd euró értékben nyújt segítséget a mediterrán országoknak. 
Africa  Afrika 
Relations between Europe and sub-Saharan Africa go back a long way.  Az Európa és a Fekete-Afrikai országok közötti kapcsolatok szintén nagy múltra tekintenek vissza. 
With the Treaty of Rome in 1957, the former colonies and overseas territories of some EEC member states became the Community’s associates.  Az 1957-es Római szerzõdéssel bizonyos EGK országok korábbi gyarmatai és tengerentúli területei a Közösség társult országai lettek. 
Decolonisation, which began in the early 1960s, turned this link into a different kind of association – an association between sovereign countries.  Ez a kapcsolat a gyarmati birodalom a 60-as évek elején elkezdõdõ szétesése folytán másfajta – immáron szuverén államok közötti – szövetséggé minõsült át. 
The Cotonou Agreement, signed in June 2000 in the capital of Benin, marked a new stage in the EU’s development policy.  A 2000 júniusában a Benin fõvárosában aláírt Cotonou-i Egyezmény új mérföldkövet jelentett az Unió fejlesztési politikájában. 
The Agreement, between the European Union and the African, Caribbean and Pacific (ACP) countries, is the most ambitious and far-reaching trade and aid agreement ever concluded between developed and developing countries.  It followed on from the Lomé Convention – originally signed in 1975 in the capital of Togo and subsequently updated at regular intervals.  Az Európai Unió valamint az afrikai, karibi és csendes-óceáni (ún. AKCs) államok közötti megállapodás a fejlett és a fejlõdõ országok között valaha megkötött megállapodások közül a legambiciózusabb és a legmesszebbre mutató kereskedelmi és segélyezési paktum, melynek elõzménye az eredetileg 1975-ben Togo fõvárosában aláírt, és következetesen, szabályos idõközönként frissített Loméi Egyezmény volt. 
The basic aim of the Agreement remains the same as that of the Lomé Convention: “to promote and expedite the economic, cultural and social development of the ACP states and to consolidate and diversify their relations [with the European Union and its member states] in a spirit of solidarity and mutual interest”.  Az Egyezmény legfontosabb célja továbbra is ugyanaz, mint a Loméi Egyezményé, azaz: „hogy elõmozdítsák és felgyorsítsák az AKCS-államok gazdasági, kulturális és szociális fejlõdését, és hogy a kölcsönös érdek alapján és a szolidaritás szellemében konszolidálják és változatossá tegyék (az Európai Unióval és tagállamaival fenntartott) kapcsolataikat.” 
The focus of Lomé was on trade relations and market access: the Cotonou Agreement has a broader scope.  For example, it introduces new procedures for dealing with human rights abuses.  Míg Loméban a hangsúly a kereskedelmi kapcsolatokon és a piacra való bejutáson volt, a Cotonou-i Egyezmény már tágabb horizontokban gondolkodik, s például új eljárásokat vezet be az emberi jogokkal való visszaélések kezelése terén. 
The European Union has granted special trading concessions to the least developed countries, 39 of which are signatories to the Agreement.  Az Európai Unió különleges kereskedelmi engedményeket juttat a legkevésbé fejlett országoknak, melyek közül 39 állam írta alá az Egyezményt. 
As of 2005, they can export practically any type of product to the EU, duty free.  2005 óta ezek az országok gyakorlatilag bármely terméket vámmentesen exportálhatnak az uniós piacra. 
The European Development Fund finances the ACP programmes from a budget of €13.5 billion over a seven-year period.  Az Európai Fejlesztési Alap egy hét éves periódusra közel 13,5 milliárd eurós költségvetést különített el az AKCs–országok programjainak finanszírozására. 
This is in addition to €9.5 billion left over from the previous funds and €1.7 billion lent by the European Investment Bank.  Ehhez még hozzájön az elõzõ alapokból megmaradt 9,5 milliárd euró, valamint az Európai Beruházási Bank által biztosított 1,7 milliárd eurós pénzösszeg is.
