KISKUNHALAS LACE MUSEUM  HALASI CSIPKEMÚZEUM 
In the small town of Kiskunhalas, located in southern Hungary, the tradition of lace making dates back around 100 years.  A Magyarország déli részén elterülõ kisvárosban, Kiskunhalason, a csipkevarrásnak közel 100 éves hagyománya van. 
During the last century, the lace produced in Kiskunhalas was a worthy rival to the lace produced in Brussels, and it received the top prize in several world exhibitions.  A halasi csipke az elmúlt évszázad folyamán méltó vetélytársa lett a brüsszeli csipkének, több világkiállításon jutalmazták nagydíjjal. 
Many famous personalities, including Pope John Paul II, the wives of the French and Czech presidents, the Empress of Japan, and Queen Elizabeth II of England, have received this traditional Hungarian product as a gift from the Hungarian State.  Olyan hírességek kapták ajándékba e hungarikumot a magyar államtól, mint II. János Pál pápa, a francia és a cseh köztársasági elnök felesége, a japán császárné vagy II. Erzsébet brit uralkodó. 
The lace is made from gossamer-thin, tightly twisted linen thread, and the art requires enormous patience.  A sok türelmet igénylõ csipkevarrás leheletfinom, erõsen sodrott len cérnával történik. 
The work is extremely time-consuming and meticulous, which makes the price of lace per gram comparable to that of gold.  Elkészítése roppant idõigényes, aprólékos kézimunka, ezért a csipke grammonkénti értéke az aranyéval vetekszik. 
The lace is produced according to century-old designs, and traditional motifs are still in use today.  A kézimunkák évszázados tervek alapján, az eredeti motívumok felhasználásával készülnek napjainkban is. 
The permanent exhibition at the Lace Museum provides an insight into the past and present of lace making in Kiskunhalas.  A Csipkemúzeum állandó kiállításán megtekinthetõ a halasi csipke múltja és jelene. 
Visitors can follow the process of lace making and marvel at this beautiful and highly skilled craft.  A látogatóknak lehetõségük van személyesen is figyelemmel kísérni a csipkevarrás, jó szemet és sok türelmet igénylõ, folyamatát. 
