Feszty Rotunda  A Feszty-körkép 
The story of Ópusztaszer's most important sight began in Paris back in the 1890's.  Ópusztaszer legfõbb nevezetességének története az 1890-es évek elején, Párizsban kezdõdött. 
Around this time, a work by the painting duo of Detaille and Neuville - a rotunda depicting a Napoleonic battle - was a great success in the French capital.  A francia fõvárosban akkortájt hatalmas sikert aratott a Detaille és Neuville festõpáros munkája, egy napóleoni csatát ábrázoló körkép. 
This left a great impression on Árpád Feszty, who was visiting the city by floating along the Seine.  On his return home, he resolved to tell a similar story of the Biblical flood through his own painting.  A Szajna menti városba látogató Feszty Árpádra óriási hatást tett a látvány, hazatérve elhatározta, hasonló módon megfesti a bibliai özönvíz történetét. 
His father-in-law, the writer, Mór Jókai (who was also knew how to use a paintbrush), later suggested that it would be better to choose a Hungarian theme in light of the approaching millennium celebration for the Hungarian Conquest.  Ám apósa, az író Jókai Mór (aki maga is ügyesen bánt az ecsettel) javasolta, hogy a honfoglalás közelgõ millenniumára való tekintettel válasszon inkább magyar témát. 
This is how the Conquest was chosen as the subject of the rotunda and how it received the title "Arrival of the Hungarians".  Így lett a körkép témája a honfoglalás, a címe pedig a Magyarok Bejövetele. 
Many years later, this masterpiece was on the verge of destruction and it took four years to renovate and restore it.  Késõbb a megsemmisülés határán álló mestermû helyreállítása és restaurálása négy évet vett igénybe. 
Since 1995, it once again became possible to visit the famous work again in its renovated form.  1995 óta megújult formában látogatható. 
In addition to the painting that covers 1,800 square meters, this national memorial, situated some 25km from Szeged, conjures up the past by virtue of its history exhibitions, reconstructed buildings, and furnishings, along with its objects recalling bygone eras, waxworks and live presentations.  Az 1800 négyzetméteres festményen kívül történelmi kiállítások, rekonstruált épületek, letûnt korokat idézõ berendezések és használati tárgyak, panoptikum és élõ bemutatók idézik a múltat a Szegedtõl mintegy 25 km-re fekvõ nemzeti emlékhelyen. 
