Albrecht Dürer - Portrait of a Man  Albrecht Dürer - Férfiképmás 
This is one of the most famous paintings in the Museum of Fine Arts.  A Szépmûvészeti Múzeum gyûjteményének egyik leghíresebb képe. 
The black damask cloak with its fur collar, typical of men's fashion at the time of the German renaissance, and the hairnet over the long hair, are both indicative of wealth.  A festményen a német reneszánsz férfidivatját reprezentáló prémgalléros fekete damasztköpeny, és a hosszú hajat összefogó hajháló a jómódot jelzi. 
The picture clearly portrays the extremely open features and emotions of the young man.  A kép jól láttatja a fiatal férfi rendkívüli nyíltsággal feltárulkozó arcvonásait és érzelmeit. 
Dürer painted the hair and eyebrows using an extremely thin brush, which is a device often employed in his portrait painting.  Dürer hajszálvékony ecsettel festette meg a hajat és a szemöldököt – ez portréfestészetének egyik gyakran használt eleme. 
The smile on the tightly sealed lips has a striking resemblance to the works of Leonardo da Vinci.  Az összeszorított ajkak mosolya is ismerõs – Leonardo da Vinci mûveirõl. 
Now there are further works by Dürer for the public to admire in the Museum of Fine Arts.  Dürernek nemcsak ez a képe látható most a Szépmûvészetiben. 
One can marvel at the 3.5 x 3-metre woodcut and at one of the largest prints ever produced, which are the 36 sheets that make up the Triumphal Arch of Emperor Maximilian I.  The series of engravings on the Triumphal Procession of Emperor Maximilian I could actually be stretched out to over 50 metres and utilize 135 individual sheets.  Október 9-ig tart nyitva az a tárlat, melyen megcsodálható a sokszorosított grafika történetének legnagyobb méretû, 36 lapból összeállított 3,5x 3 méteres fametszete, az I. Miksa császár diadalkapuja, és a több mint 50 méter hosszú 135 lapból álló fametszetsorozat, az I. Miksa császár diadalmenete. 
Alongside other renaissance masters, Dürer took an active role in the creation of both of these unique works.  Mindkettõ megalkotásában más reneszánsz mesterek mellett tevékenyen részt vett Dürer is. 
